 spring:

# --Added By Rabi -Start --- #   
#   datasource:
#     url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
#     username: ${MYSQL_USER}
#     password: ${MYSQL_PASSWORD}


   datasource:
     url: jdbc:h2:mem:testdb
     driverClassName: org.h2.Driver
     username: sa
     password: password
 # --Added By Rabi  End--- #   
  
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect  #Added By Rabi
      hibernate:
        ddl-auto: update
        show-sql: true
  
   application:
      name: AuthenticationService
      
      


 server:
      port: ${server-port:9100} 
#      ribbon.listOfServers: localhost:9100,localhost:9101,localhost:9102
#      ribbon.eureka.enabled: true
  
# eureka:
#   client :
#    eureka-server-port : 8761

 jwt:
  security:
    secret: supersecret
   